version: "3"
services:
  app:
    container_name: flask_app
    build: ./Backend
    ports:
      - "5000:5000"
    # volumes:
    #   - ./app:/app
    depends_on:
      - db

  db:
    container_name: sqlite_db
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      #Modify following line
      - ./sqlite_db/sqlite3:/root/db/
    ports:
      - '9000:9000' # expose ports - HOST:CONTAINER
    restart: unless-stopped